apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-try7
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jqos-tenant/rhtap-demo-app/hacbs-test-project-try7@sha256:1f24764e221567af639d9fe701093cbe5b964fe81b53dbbfeb34b3e305b11481
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
