apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-try7
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jqos-tenant/rhtap-demo-app/hacbs-test-project-try7@sha256:b76f7373982c2e6b2a683590c33af18c05e833def0ce0685c2365937d3c1931c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
